apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: Opaque
data:
    postgresql-db-username: YmV6dW5lc2g=
    postgresql-db-password: YmV6dWRqYW5nbw==
    postgresql-db-name: aGVsbG8tZGphbmdv
    secret-key: Zm9v