apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-depl
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: bezu/django-on-docker_db
        ports:
        - containerPort: 8888
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-db-username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-db-password
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef:
              name: postgresql-secret
              key:  postgresql-db-name
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
